%token <string> IDENT
%token <string> DATA
%token <string> STRING
%token <string> NUMBER
%token <string> HEXLIT
%token EOF LBRACE RBRACE FUNCTION LPAREN RPAREN ARROW LET COLONEQUAL IF SWITCH CASE DEFAULT FOR BREAK CONTINUE LEAVE COMMA OBJECT CODE

%%
